on: [push, workflow_dispatch]
name: x86_64 ISO image
jobs:
  build-iso:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone reduceOS repository
        uses: actions/checkout@v2
      - name: Download Docker image
        run: docker pull techdude17/reduceos-docker:x86_64
      - name: Build OS
        run: docker run -v ${GITHUB_WORKSPACE}:/opt/reduceOS -t techdude17/reduceos-docker:x86_64 /opt/build/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: build-output/hexahedron.iso